import type { Destination, DestinationCategory } from './types';

export type { Destination, DestinationCategory };

export const destinations: Destination[] = [
  {
    id: '1',
    name: 'Pantai Klayar',
    category: 'Pantai',
    description: 'Pantai eksotis dengan Seruling Samudra dan formasi batu karang unik.',
    longDescription: 'Pantai Klayar adalah salah satu ikon wisata Pacitan yang paling terkenal. Dikenal karena pasir putihnya yang lembut, ombak yang menantang, dan formasi batu karang yang megah menyerupai Sphinx. Fitur paling unik adalah "Seruling Samudra", sebuah celah di batu karang yang menyemburkan air laut ke udara disertai suara mirip seruling saat ombak besar datang.',
    address: 'Desa Kalak, Kecamatan Donorojo, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.2215, lng: 110.9501 },
    operatingHours: '24 Jam',
    ticketPrice: 'Rp 15.000',
    facilities: ['Parkir Luas', 'Warung Makan', 'Toilet', 'Mushola', 'Gazebo'],
    rating: 4.8,
    reviews: [
      { user: 'Andi S.', comment: 'Pemandangannya luar biasa! Seruling Samudranya keren banget.', rating: 5 },
      { user: 'Citra W.', comment: 'Pantainya bersih dan indah. Wajib dikunjungi kalau ke Pacitan.', rating: 5 },
    ],
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: '2',
    name: 'Goa Gong',
    category: 'Goa',
    description: 'Goa terindah di Asia Tenggara dengan stalaktit dan stalagmit menakjubkan.',
    longDescription: 'Goa Gong sering disebut sebagai goa terindah di Asia Tenggara karena keindahan formasi stalaktit dan stalagmitnya yang berkilauan saat disinari cahaya. Di dalam goa, terdapat jalur setapak yang aman dan pencahayaan warna-warni yang menambah kesan magis. Nama "Gong" diambil dari salah satu batu yang jika dipukul akan mengeluarkan bunyi seperti gong.',
    address: 'Desa Bomo, Kecamatan Punung, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.1818, lng: 111.0024 },
    operatingHours: '07:00 - 17:00',
    ticketPrice: 'Rp 20.000',
    facilities: ['Parkir', 'Pemandu Wisata', 'Toilet', 'Toko Souvenir', 'Warung Makan'],
    rating: 4.9,
    reviews: [
      { user: 'Budi P.', comment: 'Seperti masuk ke dunia lain. Sangat direkomendasikan!', rating: 5 },
      { user: 'Dewi L.', comment: 'Pencahayaannya bagus, membuat goa jadi sangat cantik.', rating: 4 },
    ],
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: '3',
    name: 'Pantai Banyu Tibo',
    category: 'Pantai',
    description: 'Keunikan pantai dengan air terjun yang langsung jatuh ke laut.',
    longDescription: 'Pantai Banyu Tibo menawarkan pemandangan yang sangat langka dan unik, yaitu sebuah air terjun tawar yang airnya langsung jatuh dari tebing ke bibir pantai dan menyatu dengan air laut. Pengunjung bisa bermain di bawah air terjun sambil menikmati suasana pantai. Nama "Banyu Tibo" sendiri berasal dari bahasa Jawa yang berarti "air jatuh".',
    address: 'Desa Widoro, Kecamatan Donorojo, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.2250, lng: 110.9780 },
    operatingHours: '24 Jam',
    ticketPrice: 'Rp 10.000',
    facilities: ['Parkir', 'Warung Kecil', 'Toilet'],
    rating: 4.7,
    reviews: [
      { user: 'Eka F.', comment: 'Unik banget ada air terjun di pantai. Pemandangan sunsetnya juga bagus.', rating: 5 },
    ],
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: '4',
    name: 'Sungai Maron',
    category: 'Wisata Alam',
    description: 'Dijuluki "Amazon-nya Indonesia" karena suasana sungainya yang hijau dan asri.',
    longDescription: 'Menyusuri Sungai Maron dengan perahu akan memberikan pengalaman serasa di Sungai Amazon. Kiri dan kanan sungai dihiasi oleh rimbunnya pohon kelapa dan vegetasi tropis lainnya. Airnya yang jernih berwarna kehijauan membuat suasana sangat tenang dan damai. Ini adalah tempat yang sempurna untuk bersantai dan menikmati alam.',
    address: 'Desa Dersono, Kecamatan Pringkuku, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.1856, lng: 111.0189 },
    operatingHours: '07:00 - 17:00',
    ticketPrice: 'Rp 100.000 / perahu',
    facilities: ['Area Parkir', 'Sewa Perahu', 'Warung Makan', 'Toilet'],
    rating: 4.6,
    reviews: [
      { user: 'Fajar R.', comment: 'Sungainya bersih, udaranya sejuk. Pengalaman yang menenangkan.', rating: 5 },
      { user: 'Gita H.', comment: 'Worth it banget sewa perahu seharian!', rating: 4 },
    ],
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: '5',
    name: 'Pantai Srau',
    category: 'Pantai',
    description: 'Memiliki tiga spot pantai yang indah dengan pasir putih dan batu karang.',
    longDescription: 'Pantai Srau adalah kompleks pantai yang terdiri dari tiga bagian atau "spot" pantai yang masing-masing memiliki karakteristik unik. Pasir putihnya yang sangat halus dan air lautnya yang biru jernih menjadi daya tarik utama. Tempat ini cocok untuk bersantai, bermain pasir, atau sekadar menikmati keindahan alam yang masih sangat alami.',
    address: 'Desa Candi, Kecamatan Pringkuku, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.2166, lng: 111.0500 },
    operatingHours: '24 Jam',
    ticketPrice: 'Rp 5.000',
    facilities: ['Parkir', 'Gazebo', 'Warung', 'Toilet', 'Area Camping'],
    rating: 4.7,
    reviews: [],
    images: ['https://placehold.co/600x400.png'],
  },
  {
    id: '6',
    name: 'Goa Tabuhan',
    category: 'Goa',
    description: 'Goa bersejarah yang bisa "dimainkan" seperti alat musik gamelan.',
    longDescription: 'Goa Tabuhan tidak hanya menawarkan keindahan stalaktit dan stalagmit, tetapi juga keunikan sejarah dan budaya. Beberapa batu di dalam goa ini jika dipukul dapat menghasilkan nada-nada yang mirip dengan alat musik gamelan Jawa. Dahulu, goa ini digunakan sebagai tempat pertunjukan "wayang beber" dengan iringan musik dari batu-batu tersebut.',
    address: 'Desa Wareng, Kecamatan Punung, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.1500, lng: 111.0167 },
    operatingHours: '08:00 - 16:00',
    ticketPrice: 'Rp 10.000',
    facilities: ['Parkir', 'Pemandu', 'Sewa Alat Musik Batu', 'Toilet'],
    rating: 4.5,
    reviews: [],
    images: ['https://placehold.co/600x400.png'],
  }
];
