import type { Destination, DestinationCategory } from './types';

export type { Destination, DestinationCategory };

export const destinations: Destination[] = [
  {
    id: '1',
    name: 'Pantai Klayar',
    category: 'Pantai',
    description: 'Pantai eksotis dengan Seruling Samudra dan formasi batu karang unik.',
    longDescription: 'Pantai Klayar adalah salah satu ikon wisata Pacitan yang paling terkenal. Dikenal karena pasir putihnya yang lembut, ombak yang menantang, dan formasi batu karang yang megah menyerupai Sphinx. Fitur paling unik adalah "Seruling Samudra", sebuah celah di batu karang yang menyemburkan air laut ke udara disertai suara mirip seruling saat ombak besar datang.',
    address: 'Desa Kalak, Kecamatan Donorojo, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.2215, lng: 110.9501 },
    operatingHours: '24 Jam',
    ticketPrice: 'Rp 15.000',
    facilities: ['Parkir Luas', 'Warung Makan', 'Toilet', 'Mushola', 'Gazebo'],
    rating: 4.8,
    reviews: [
      { user: 'Andi S.', comment: 'Pemandangannya luar biasa! Seruling Samudranya keren banget.', rating: 5 },
      { user: 'Citra W.', comment: 'Pantainya bersih dan indah. Wajib dikunjungi kalau ke Pacitan.', rating: 5 },
    ],
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: '2',
    name: 'Goa Gong',
    category: 'Goa',
    description: 'Goa terindah di Asia Tenggara dengan stalaktit dan stalagmit menakjubkan.',
    longDescription: 'Goa Gong sering disebut sebagai goa terindah di Asia Tenggara karena keindahan formasi stalaktit dan stalagmitnya yang berkilauan saat disinari cahaya. Di dalam goa, terdapat jalur setapak yang aman dan pencahayaan warna-warni yang menambah kesan magis. Nama "Gong" diambil dari salah satu batu yang jika dipukul akan mengeluarkan bunyi seperti gong.',
    address: 'Desa Bomo, Kecamatan Punung, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.1818, lng: 111.0024 },
    operatingHours: '07:00 - 17:00',
    ticketPrice: 'Rp 20.000',
    facilities: ['Parkir', 'Pemandu Wisata', 'Toilet', 'Toko Souvenir', 'Warung Makan'],
    rating: 4.9,
    reviews: [
      { user: 'Budi P.', comment: 'Seperti masuk ke dunia lain. Sangat direkomendasikan!', rating: 5 },
      { user: 'Dewi L.', comment: 'Pencahayaannya bagus, membuat goa jadi sangat cantik.', rating: 4 },
    ],
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: '3',
    name: 'Pantai Banyu Tibo',
    category: 'Pantai',
    description: 'Keunikan pantai dengan air terjun yang langsung jatuh ke laut.',
    longDescription: 'Pantai Banyu Tibo menawarkan pemandangan yang sangat langka dan unik, yaitu sebuah air terjun tawar yang airnya langsung jatuh dari tebing ke bibir pantai dan menyatu dengan air laut. Pengunjung bisa bermain di bawah air terjun sambil menikmati suasana pantai. Nama "Banyu Tibo" sendiri berasal dari bahasa Jawa yang berarti "air jatuh".',
    address: 'Desa Widoro, Kecamatan Donorojo, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.2250, lng: 110.9780 },
    operatingHours: '24 Jam',
    ticketPrice: 'Rp 10.000',
    facilities: ['Parkir', 'Warung Kecil', 'Toilet'],
    rating: 4.7,
    reviews: [
      { user: 'Eka F.', comment: 'Unik banget ada air terjun di pantai. Pemandangan sunsetnya juga bagus.', rating: 5 },
    ],
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: '4',
    name: 'Sungai Maron',
    category: 'Wisata Alam',
    description: 'Dijuluki "Amazon-nya Indonesia" karena suasana sungainya yang hijau dan asri.',
    longDescription: 'Menyusuri Sungai Maron dengan perahu akan memberikan pengalaman serasa di Sungai Amazon. Kiri dan kanan sungai dihiasi oleh rimbunnya pohon kelapa dan vegetasi tropis lainnya. Airnya yang jernih berwarna kehijauan membuat suasana sangat tenang dan damai. Ini adalah tempat yang sempurna untuk bersantai dan menikmati alam.',
    address: 'Desa Dersono, Kecamatan Pringkuku, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.1856, lng: 111.0189 },
    operatingHours: '07:00 - 17:00',
    ticketPrice: 'Rp 100.000 / perahu',
    facilities: ['Area Parkir', 'Sewa Perahu', 'Warung Makan', 'Toilet'],
    rating: 4.6,
    reviews: [
      { user: 'Fajar R.', comment: 'Sungainya bersih, udaranya sejuk. Pengalaman yang menenangkan.', rating: 5 },
      { user: 'Gita H.', comment: 'Worth it banget sewa perahu seharian!', rating: 4 },
    ],
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: '5',
    name: 'Pantai Srau',
    category: 'Pantai',
    description: 'Memiliki tiga spot pantai yang indah dengan pasir putih dan batu karang.',
    longDescription: 'Pantai Srau adalah kompleks pantai yang terdiri dari tiga bagian atau "spot" pantai yang masing-masing memiliki karakteristik unik. Pasir putihnya yang sangat halus dan air lautnya yang biru jernih menjadi daya tarik utama. Tempat ini cocok untuk bersantai, bermain pasir, atau sekadar menikmati keindahan alam yang masih sangat alami.',
    address: 'Desa Candi, Kecamatan Pringkuku, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.2166, lng: 111.0500 },
    operatingHours: '24 Jam',
    ticketPrice: 'Rp 5.000',
    facilities: ['Parkir', 'Gazebo', 'Warung', 'Toilet', 'Area Camping'],
    rating: 4.7,
    reviews: [],
    images: ['https://placehold.co/600x400.png'],
  },
  {
    id: '6',
    name: 'Goa Tabuhan',
    category: 'Goa',
    description: 'Goa bersejarah yang bisa "dimainkan" seperti alat musik gamelan.',
    longDescription: 'Goa Tabuhan tidak hanya menawarkan keindahan stalaktit dan stalagmit, tetapi juga keunikan sejarah dan budaya. Beberapa batu di dalam goa ini jika dipukul dapat menghasilkan nada-nada yang mirip dengan alat musik gamelan Jawa. Dahulu, goa ini digunakan sebagai tempat pertunjukan "wayang beber" dengan iringan musik dari batu-batu tersebut.',
    address: 'Desa Wareng, Kecamatan Punung, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.1500, lng: 111.0167 },
    operatingHours: '08:00 - 16:00',
    ticketPrice: 'Rp 10.000',
    facilities: ['Parkir', 'Pemandu', 'Sewa Alat Musik Batu', 'Toilet'],
    rating: 4.5,
    reviews: [],
    images: ['https://placehold.co/600x400.png'],
  },
  {
    id: '7',
    name: 'Pantai Teleng Ria',
    category: 'Pantai',
    description: 'Pantai populer dekat pusat kota dengan fasilitas lengkap dan ombak tenang.',
    longDescription: 'Pantai Teleng Ria adalah destinasi favorit keluarga karena lokasinya yang sangat dekat dengan pusat kota Pacitan. Pantai ini memiliki bibir pantai yang panjang, ombak yang relatif tenang, dan fasilitas yang sangat lengkap, mulai dari penginapan, restoran, hingga area bermain anak. Sangat cocok untuk berenang dan bersantai.',
    address: 'Kelurahan Sidoharjo, Kecamatan Pacitan, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.2100, lng: 111.1000 },
    operatingHours: '24 Jam',
    ticketPrice: 'Rp 10.000',
    facilities: ['Parkir', 'Hotel', 'Restoran', 'Kolam Renang', 'Area Bermain', 'Toilet'],
    rating: 4.5,
    reviews: [],
    images: ['https://placehold.co/600x400.png'],
  },
  {
    id: '8',
    name: 'Pantai Watu Karung',
    category: 'Pantai',
    description: 'Surga bagi para peselancar dengan ombak kelas dunia dan pulau karang ikonik.',
    longDescription: 'Pantai Watu Karung adalah primadona bagi para peselancar profesional dari seluruh dunia. Ombaknya yang besar dan berbentuk tabung (barrel) menjadi tantangan tersendiri. Selain untuk berselancar, pantai ini juga sangat indah dengan pasir putih, air biru jernih, dan pulau-pulau karang eksotis di tengah laut.',
    address: 'Desa Watukarung, Kecamatan Pringkuku, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.2325, lng: 110.9921 },
    operatingHours: '24 Jam',
    ticketPrice: 'Rp 5.000',
    facilities: ['Parkir', 'Homestay', 'Warung Makan', 'Penyewaan Papan Selancar', 'Toilet'],
    rating: 4.8,
    reviews: [],
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: '9',
    name: 'Beiji Park',
    category: 'Wisata Alam',
    description: 'Taman alam di atas bukit dengan pemandangan 360 derajat ke laut lepas.',
    longDescription: 'Beiji Park adalah taman rekreasi yang berada di atas perbukitan Desa Dadapan. Dari sini, pengunjung dapat menikmati pemandangan spektakuler ke arah Samudra Hindia dan perbukitan karst Pacitan. Terdapat banyak spot foto instagramable, taman bunga, dan gazebo untuk bersantai.',
    address: 'Desa Dadapan, Kecamatan Pringkuku, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.2052, lng: 111.0205 },
    operatingHours: '08:00 - 17:00',
    ticketPrice: 'Rp 10.000',
    facilities: ['Parkir', 'Spot Foto', 'Kafe', 'Toilet', 'Taman Bunga'],
    rating: 4.6,
    reviews: [],
    images: ['https://placehold.co/600x400.png'],
  },
  {
    id: '10',
    name: 'Soto Pacitan Mbah Suti',
    category: 'Kuliner',
    description: 'Soto legendaris dengan kuah bening khas dan potongan daging ayam kampung.',
    longDescription: 'Soto Pacitan Mbah Suti adalah salah satu kuliner legendaris yang wajib dicoba. Berbeda dari soto pada umumnya, soto ini memiliki kuah bening yang segar dengan bumbu rempah yang khas. Disajikan dengan potongan daging ayam kampung, tauge, dan perkedel singkong, menciptakan cita rasa yang unik dan otentik.',
    address: 'Jl. Ahmad Yani, Baleharjo, Kecamatan Pacitan, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.1950, lng: 111.1000 },
    operatingHours: '07:00 - 15:00',
    ticketPrice: 'Rp 15.000 / porsi',
    facilities: ['Tempat Duduk', 'Parkir Terbatas'],
    rating: 4.7,
    reviews: [],
    images: ['https://placehold.co/600x400.png'],
  },
  {
    id: '11',
    name: 'Monumen Jenderal Sudirman',
    category: 'Budaya',
    description: 'Monumen bersejarah untuk mengenang rute gerilya Panglima Besar Jenderal Sudirman.',
    longDescription: 'Monumen ini didirikan untuk mengenang perjuangan Panglima Besar Jenderal Sudirman saat memimpin perang gerilya melawan Belanda. Lokasinya berada di puncak bukit di Desa Pakis Baru, yang merupakan salah satu titik penting dalam rute gerilyanya. Selain nilai sejarah, tempat ini menawarkan pemandangan alam Pacitan dari ketinggian.',
    address: 'Desa Pakis Baru, Kecamatan Nawangan, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -7.9961, lng: 111.1612 },
    operatingHours: '08:00 - 17:00',
    ticketPrice: 'Rp 5.000',
    facilities: ['Area Parkir', 'Museum Kecil', 'Toilet', 'Warung'],
    rating: 4.5,
    reviews: [],
    images: ['https://placehold.co/600x400.png'],
  },
  {
    id: '12',
    name: 'Pemandian Air Hangat Tirto Husodo',
    category: 'Wisata Alam',
    description: 'Pemandian air panas alami yang dipercaya baik untuk kesehatan kulit.',
    longDescription: 'Pemandian Air Hangat Tirto Husodo adalah tempat relaksasi yang populer di Pacitan. Sumber air panasnya mengandung belerang yang dipercaya memiliki khasiat untuk menyembuhkan penyakit kulit dan merelaksasi otot. Tersedia kolam-kolam pemandian umum dan kamar-kamar privat untuk kenyamanan pengunjung.',
    address: 'Desa Karangrejo, Kecamatan Arjosari, Kabupaten Pacitan, Jawa Timur',
    gps: { lat: -8.0989, lng: 111.1398 },
    operatingHours: '07:00 - 17:00',
    ticketPrice: 'Rp 10.000 (umum), Rp 20.000 (privat)',
    facilities: ['Kolam Rendam', 'Kamar Mandi Privat', 'Parkir', 'Kantin', 'Toilet'],
    rating: 4.4,
    reviews: [],
    images: ['https://placehold.co/600x400.png'],
  }
];
